language: node_js
node_js:
- 6
deploy:
  provider: heroku
  app: solidarize-web-dev
  api_key:
    secure: rM4H+/DHEfHKot2er9SjquNs7g8pp5vvPCkFfzV8EnKx0mEJ4b8YD8Hc08HyXNjd6tfKwoJejDYXKAHG5Zxp/oykcZW1D+sISjTD6Vqnqwy4uhSnX8EgrHoLdpEUkiVZFlDCeFP9ojqWCBf1A/BZyfjCu5mOVromnBzVHee/5tO8uJqj94hsJwiRzjQZVe3GQIjPq6wPSRQmzskvU9WNz8T5i3mR9OS2ChA3ceVmmnoO476sgy2hU7aSyjDQ3SIC0lz8PZVB0R88Xz353lGoZ1hKiBiDfNhRidy4JaxHeDwQsz9BhDLolrUH9iRcS9I+8KK4Q0eEwX0MGTj7KRbXkPehgiBhf8KVGEk8XeYf1rgY9+oy/JlmtB5Py/ypoV47LdwL3+2TpBFXteztZmLgOWPcN7HGLJcWzuS2BGKtAgY3b1lGjC5JBjDdlMJgclgayNiuGpDKM3NYWRTy6IDw1xlppINfF96SylBLIcgFdYR3Nme52hBykisANIVlAZbXumLZbK7i73x/LoNoCZP4hxGJ3FtSTfJFGaaINqt1HF4qU9uTUiYV4l5mg8Vlcg3QxyAySusBYdqWFGvJm6TBq5JVMIipT3sJo8rLTm6Sd7ug0o7PHWaL8675M+YMZ4hLqwS6Y42Fs8WP67SMUKYfINedbM/fnXq952apJIwdZD8=
